### ISSUE TITLE
Some towns are missing all of their data.

### ISSUE THREAD

**Issue by voogt** [landinfotech/AIMexe#5]
Had a look at the restored civitas database I created on Pgadmin and confirmed that there is no data in the feature_base table for the towns. Did we include all towns in the export script?

**Comment by edvandenberg** [comment]
Believe the aim clients will be using blank databases, so it wont matter for the launch. Not sure why some towns data did not restore but lets leave it for now, I'll update if we need to address it in the future.

**Comment by voogt** [comment]
Hi @edvandenberg can you let me know which towns are not showing for you that I can check?

**Comment by edvandenberg** [comment]
There are probably 10-15 towns without data. I'll try and restore the database again and get back to you

**Comment by edvandenberg** [comment]
Missing town now have data, thanks
