### ISSUE TITLE
No electrical network data is displayed on the map or in the classification/organization 

### ISSUE THREAD

**Issue by voogt** [landinfotech/AIMexe#7]

**Comment by edvandenberg** [comment]
Is this based on an earlier version of civitas? I still don't see any electrical data. 
Regardless I think we should just leave it for now, none of the clients that will be using the exe have electrical network data.
I'll leave this issue open for the future if we want to dress it then

**Comment by voogt** [comment]
Hi @edvandenberg this based on an updated version of civitas. I am able to view electric network for mahone bay 
![image](https://github.com/user-attachments/assets/3e4c6fd3-6fc4-4550-b426-5b4db9556e00)

**Comment by edvandenberg** [comment]
Could you send me that latest export script? I'll try to restore the civitas database again

**Comment by edvandenberg** [comment]
Thanks Juanique I'm able to see electrical after resorting with your latest script
